# Generated by Django 3.2.8 on 2021-10-20 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("couriers", "0001_initial"),
        ("customers", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="shop.shop",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_completed", models.BooleanField(default=False)),
                ("completed_time", models.DateTimeField(blank=True)),
                ("total_price", models.FloatField(default=0)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="couriers.courier",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                ("goods", models.ManyToManyField(to="shop.Good")),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.shop"
                    ),
                ),
            ],
        ),
    ]
