# Generated by Django 3.2.8 on 2021-10-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_auto_20211020_1646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="completed_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
