# Generated by Django 3.2.8 on 2021-10-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("couriers", "0002_alter_shift_courier"),
        ("shop", "0003_alter_order_completed_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="courier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="couriers.courier",
            ),
        ),
    ]
