# Generated by Django 3.2.8 on 2021-11-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='icon',
            field=models.ImageField(default='shops/default.png', upload_to='shops/'),
        ),
    ]
