# Generated by Django 3.2.8 on 2021-12-13 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.good')),
            ],
        ),
    ]
