# Generated by Django 3.2.8 on 2022-01-14 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 14, 13, 22, 381031)),
            preserve_default=False,
        ),
    ]
