# Generated by Django 3.2.8 on 2021-10-20 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.IntegerField()),
                (
                    "vehicle",
                    models.CharField(
                        choices=[
                            ("CAR", "Машина"),
                            ("BIKE", "Велосипед"),
                            ("WALK", "Пешком"),
                        ],
                        max_length=4,
                    ),
                ),
                ("telephone", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_parity",
                    models.CharField(
                        choices=[("even", "Четный"), ("odd", "Нечетный")], max_length=4
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="couriers.courier",
                    ),
                ),
            ],
        ),
    ]
