# Generated by Django 3.2.8 on 2021-10-20 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("couriers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="couriers.courier",
            ),
        ),
    ]
