# Generated by Django 3.2.8 on 2021-10-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("couriers", "0002_alter_shift_courier"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="week_day",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
