# Generated by Django 3.2.8 on 2021-11-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_courier'),
        ('couriers', '0003_shift_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='dormitory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.dormitory'),
            preserve_default=False,
        ),
    ]
